---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(mosaic)
library(dcData)
head(BabyNames)
```
## chapter 17
##17.1
```{r}
data("BabyNames")
BabyNames %>%
  filter(sex == "M") %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  filter(grepl("[aeiou]$", name)) %>%
  arrange(desc(total)) %>%
  head(10)
```

#17.12
```{r}
BabyNames %>%
  filter(grepl("[ ]", name, ignore.case = TRUE)) %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  arrange(desc(total)) %>%
  head(10)
```

#17.13
```{r}
BabyNames %>%
  filter(grepl("[Jj]oe$", name, ignore.case = TRUE)) %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  arrange(desc(total)) %>%
  head(10)
BabyNames %>%
  filter(grepl(".joe$", name, ignore.case = TRUE)) %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  arrange(desc(total)) %>%
  head(10)
```


## 17.3
##([2-9][0-9]{2})[- .]([0-9]{3})[- .]([0-9]{4})

## 17.4
##1 :2 characters
##2 61 different strings
States


## 17.5
```{r}
BibleNames <- 
  readr::read_csv("https://mdbeckman.github.io/dcSupplement/data/BibleNames.csv")
BibleNames %>%
  filter(grepl("bar|dam|lory", name, ignore.case = TRUE)) %>%
  group_by(name) %>%
  head(10)
BibleNames %>%
  filter(grepl("bar$|dam$|lory$", name, ignore.case = TRUE)) %>%
  group_by(name) %>%
  head(10)

```


##17.7
```{r}
Bible_related <- BabyNames %>%
  inner_join(BibleNames) %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  arrange(desc(total)) %>%
  head(10)
Bible_related

```

