---
title: "problem 8"
output:
  html_document:
    df_print: paged
---

##Question 8.1
#geom_point()
# Add a layer of glyphs
#geom_histogram()
# Add a layer of glyphs
#ggplot()
# Construct the graphics frame
#scale_y_log10()
# Change the scale of the frame
#ylab()
# Set an axis label
#facet_wrap()
# Divide the frame into facets
#geom_segment()
# Add a layer of glyphs
#xlim()
#facet_grid()
# Divide the frame into facets

## Question 8.2
```{r}
library(mosaic)
library(tidyverse)
library(dcData)
data(CPS85)
 ggplot(data = CPS85, aes(x=wage, fill=sex)) + geom_density(adjust = 0.4) + facet_wrap(~married, ncol = 4) + labs(title = "") + theme(legend.position = "right") + xlim(0,30)
ggplot(data = CPS85, aes(x = age, y = wage)) + geom_smooth()   + aes(colour = sex) + facet_grid(married~.) + theme(legend.position = "right") + labs(title = "")
ggplot(data = CPS85, aes(x = age, y = wage)) + geom_smooth()   + aes(colour = sex) + facet_wrap(~sector, ncol = 4) + theme(legend.position = "right") + labs(title = "")
```
## Question 8.3
```{r}
ggplot(data = CPS85,
       mapping = aes(x = age, y = wage )) +
  geom_point()

ggplot(data = CPS85,
       mapping = aes(x = age, y = wage, shape = sex)) + geom_point()+theme(legend.position = "top")
ggplot(data = CPS85,
       mapping = aes(x = age, y = wage, shape = sex)) + geom_point()+facet_grid(married~.)+ geom_point()+theme(legend.position = "top")
ggplot(data = CPS85,
       mapping = aes(x = age, y = wage, shape = married)) + geom_point()+ geom_point()+theme(legend.position = "top")
```




